kind: Service
apiVersion: v1
metadata:
    name: mw-node-4-service
    namespace: madwater-rd
spec:
    ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072
    selector:
        app: node4
    type: NodePort
    sessionAffinity: None
    externalTrafficPolicy: Cluster
