apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mw-node-4-deploy
  namespace: madwater-rd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node4
    spec:
      containers:
      - name: mw-node-4
        image: mw-node-4:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8072
          protocol: TCP
